const penumbraColors = {
    base: {
        100: "#FFFDFB",
        200: "#FFF7ED",
        300: "#F2E6D4",
        400: "#CECECE",
        500: "#9E9E9E",
        600: "#636363",
        700: "#3E4044",
        800: "#24272B",
        900: "#181B1F",
    },
    red: "#DF7F78",
    orange: "#D68B47",
    yellow: "#9CA748",
    green: "#50B584",
    cyan: "#00B3C2",
    blue: "#61A3E6",
    purple: "#A48FE1",
    magenta: "#D080B6",
};

/** @type {import('tailwindcss').Config} */
export default {
    content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
    darkMode: "class",
    plugins: [require("@tailwindcss/typography")],
    theme: {
        extend: {
            // Use penumbra color scheme
            colors: {
                ...penumbraColors,
                primary: penumbraColors.blue,
                success: penumbraColors.green,
                warning: penumbraColors.orange,
                error: penumbraColors.red,
                changed: penumbraColors.blue,
                inherit: "inherit",
                current: "currentColor",
                transparent: "transparent",
            },
            screens: {
                xs: "480px",
            },
            typography: ({ theme }) => ({
                base: {
                    css: {
                        "--tw-prose-body": theme("colors.base[900]"),
                        "--tw-prose-headings": theme("colors.base[900]"),
                        "--tw-prose-lead": theme("colors.base[600]"),
                        "--tw-prose-links": theme("colors.blue"),
                        "--tw-prose-bold": theme("colors.base[900]"),
                        "--tw-prose-counters": theme("colors.base[600]"),
                        "--tw-prose-bullets": theme("colors.base[400]"),
                        "--tw-prose-hr": theme("colors.base[300]"),
                        "--tw-prose-quotes": theme("colors.base[600]"),
                        "--tw-prose-quote-borders": theme("colors.base[300]"),
                        "--tw-prose-captions": theme("colors.base[700]"),
                        "--tw-prose-code": theme("colors.base[800]"),
                        "--tw-prose-pre-code": theme("colors.base[700]"),
                        "--tw-prose-pre-bg": theme("colors.base[300]"),
                        "--tw-prose-th-borders": theme("colors.base[300]"),
                        "--tw-prose-td-borders": theme("colors.base[200]"),
                        "--tw-prose-invert-body": theme("colors.base[100]"),
                        "--tw-prose-invert-headings": theme("colors.base[100]"),
                        "--tw-prose-invert-lead": theme("colors.base[400]"),
                        "--tw-prose-invert-links": theme("colors.blue"),
                        "--tw-prose-invert-bold": theme("colors.base[100]"),
                        "--tw-prose-invert-counters": theme("colors.base[400]"),
                        "--tw-prose-invert-bullets": theme("colors.base[600]"),
                        "--tw-prose-invert-hr": theme("colors.base[700]"),
                        "--tw-prose-invert-quotes": theme("colors.base[400]"),
                        "--tw-prose-invert-quote-borders": theme("colors.base[700]"),
                        "--tw-prose-invert-captions": theme("colors.base[400]"),
                        "--tw-prose-invert-code": theme("colors.base[300]"),
                        "--tw-prose-invert-pre-code": theme("colors.base[500]"),
                        "--tw-prose-invert-pre-bg": theme("colors.base[900]"),
                        "--tw-prose-invert-th-borders": theme("colors.base[600]"),
                        "--tw-prose-invert-td-borders": theme("colors.base[700]"),
                    },
                },
            }),
            animation: {
                blink: "blink 0.5s ease-in-out infinite alternate",
            },
            keyframes: {
                blink: {
                    "0%": {
                        opacity: "1",
                    },
                    "35%": {
                        opacity: "1",
                    },
                    "65%": {
                        opacity: "0",
                    },
                    "100%": {
                        opacity: "0",
                    },
                },
            },
        },
        fontFamily: {
            mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
            body: [
                "Atkinson Hyperlegible",
                "ui-sans-serif",
                "system-ui",
                "-apple-system",
                "BlinkMacSystemFont",
                '"Segoe UI"',
                "Roboto",
                '"Helvetica Neue"',
                "Arial",
                '"Noto Sans"',
                "sans-serif",
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            default: [
                "ui-sans-serif",
                "system-ui",
                "-apple-system",
                "BlinkMacSystemFont",
                '"Segoe UI"',
                "Roboto",
                '"Helvetica Neue"',
                "Arial",
                '"Noto Sans"',
                "sans-serif",
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
        },
    },
};
